# This file is autogenerated by hidl-gen. Do not edit manually.

LOCAL_PATH := $(call my-dir)

################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.qti.hardware.wifi.supplicant-V1.1-java
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_JAVA_LIBRARIES := \
    android.hardware.wifi.supplicant-V1.0-java \
    android.hidl.base-V1.0-java \
    vendor.qti.hardware.wifi.supplicant-V1.0-java \


#
# Build ISupplicantVendorP2PIface.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorP2PIface.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorP2PIface.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorP2PIface

$(GEN): $(LOCAL_PATH)/ISupplicantVendorP2PIface.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorP2PIfaceCallback.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorP2PIfaceCallback.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorP2PIfaceCallback.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorP2PIfaceCallback

$(GEN): $(LOCAL_PATH)/ISupplicantVendorP2PIfaceCallback.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorStaIface.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorStaIface.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorStaIface.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorStaIface

$(GEN): $(LOCAL_PATH)/ISupplicantVendorStaIface.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorStaNetwork.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorStaNetwork.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorStaNetwork.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorStaNetwork

$(GEN): $(LOCAL_PATH)/ISupplicantVendorStaNetwork.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_JAVA_LIBRARY)


################################################################################

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.qti.hardware.wifi.supplicant-V1.1-java-static
LOCAL_MODULE_CLASS := JAVA_LIBRARIES

intermediates := $(call local-generated-sources-dir, COMMON)

HIDL := $(HOST_OUT_EXECUTABLES)/hidl-gen$(HOST_EXECUTABLE_SUFFIX)

LOCAL_STATIC_JAVA_LIBRARIES := \
    android.hardware.wifi.supplicant-V1.0-java-static \
    android.hidl.base-V1.0-java-static \
    vendor.qti.hardware.wifi.supplicant-V1.0-java-static \


#
# Build ISupplicantVendorP2PIface.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorP2PIface.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorP2PIface.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorP2PIface

$(GEN): $(LOCAL_PATH)/ISupplicantVendorP2PIface.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorP2PIfaceCallback.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorP2PIfaceCallback.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorP2PIfaceCallback.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorP2PIfaceCallback

$(GEN): $(LOCAL_PATH)/ISupplicantVendorP2PIfaceCallback.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorStaIface.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorStaIface.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorStaIface.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorStaIface

$(GEN): $(LOCAL_PATH)/ISupplicantVendorStaIface.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)

#
# Build ISupplicantVendorStaNetwork.hal
#
GEN := $(intermediates)/vendor/qti/hardware/wifi/supplicant/V1_1/ISupplicantVendorStaNetwork.java
$(GEN): $(HIDL)
$(GEN): PRIVATE_HIDL := $(HIDL)
$(GEN): PRIVATE_DEPS := $(LOCAL_PATH)/ISupplicantVendorStaNetwork.hal
$(GEN): PRIVATE_OUTPUT_DIR := $(intermediates)
$(GEN): PRIVATE_CUSTOM_TOOL = \
        $(PRIVATE_HIDL) -o $(PRIVATE_OUTPUT_DIR) \
        -Ljava \
        -randroid.hardware:hardware/interfaces \
        -randroid.hidl:system/libhidl/transport \
        -rvendor.qti.hardware:vendor/qcom/opensource/interfaces \
        vendor.qti.hardware.wifi.supplicant@1.1::ISupplicantVendorStaNetwork

$(GEN): $(LOCAL_PATH)/ISupplicantVendorStaNetwork.hal
	$(transform-generated-source)
LOCAL_GENERATED_SOURCES += $(GEN)
include $(BUILD_STATIC_JAVA_LIBRARY)



include $(call all-makefiles-under,$(LOCAL_PATH))
